services:
  api:
    image: jrpenagu/fast-api-mlflow:latest
    #container_name: api-inferencia
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 1.8G
          cpus: 1.5
    networks:
      - proyecto-2_default
    restart: "no"

  locust:
    build:
      context: ./locust
    container_name: locust
    ports:
      - "8089:8089"
    depends_on:
      - api
    environment:
      - LOCUST_HOST=http://api:8000
    networks:
      - proyecto-2_default
    restart: "no"

networks:
  proyecto-2_default:
    external: true
