apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-05-11T05:28:38Z"
  labels:
    kubernetes.io/metadata.name: observability
    name: observability
  name: observability
  resourceVersion: "825"
  uid: 9df237f1-1de7-4fcd-9a04-7d3a5738b03b
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
