apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: inference-api-sm
  namespace: observability
spec:
  selector:
    matchLabels:
      app: inference-api
  namespaceSelector:
    matchNames:
      - project-3-mlops
  endpoints:
    - port: "8989"
      path: /metrics
      interval: 15s
