apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-4
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/jrafaelpena/puj-mlops_-group3.git'
    targetRevision: main
    path: proyectos/proyecto-4/k8s

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: project-4

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true