[project]
name = "airflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lightgbm>=4.6.0",
    "numpy>=2.2.4",
    "optuna>=4.2.1",
    "scikit-learn>=1.6.1",
]
