apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-api
  namespace: project-3-mlops
  labels:
    app: inference-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-api
  template:
    metadata:
      labels:
        app: inference-api
    spec:
      containers:
        - name: inference-api
          image: jrpenagu/fastapi-mlflow-app:latest
          ports:
            - containerPort: 8989
          command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8989"]
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: project3
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000
            - name: POSTGRES_USER
              value: project3
            - name: POSTGRES_PASSWORD
              value: project3
            - name: POSTGRES_DB
              value: train_data
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: inference-api
  namespace: project-3-mlops
spec:
  type: NodePort
  selector:
    app: inference-api
  ports:
    - port: 8989
      targetPort: 8989
      nodePort: 30898