apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: taller-ci-cd
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      uid: prometheus
      editable: true