airflowVersion: 2.10.5
executor: LocalExecutor

image:
  repository: jrpenagu/airflow-ml
  tag: "1.0"
  pullPolicy: IfNotPresent

postgresql:
  enabled: true
  image:
    tag: "14"
  persistence:
    enabled: true
    size: 8Gi
  auth:
    postgresPassword: "MiPasswordMuySecreto123"

redis:
  enabled: true
images:
  redis:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent

dags:
  gitSync:
    enabled: true
    repo: https://github.com/jrafaelpena/puj-mlops_-group3.git
    branch: main
    rev: HEAD
    depth: 1
    subPath: proyectos/proyecto-4/apps/airflow/dags

logs:
  persistence:
    enabled: true
    size: 5Gi

ingress:
  web:
    enabled: false

webserver:
  service:
    type: ClusterIP

rbac:
  create: true

serviceAccount:
  create: true
  name: airflow-sa

workers:
  podAnnotations: {}
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi

scheduler:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

web:
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 600m
      memory: 1Gi