airflowVersion: 2.10.5

executor: KubernetesExecutor

image:
  repository: jrpenagu/airflow-ml
  tag: "1.0"
  pullPolicy: IfNotPresent

postgresql:
  enabled: true
  image:
    tag: "14"
  persistence:
    enabled: true
    size: 8Gi
  postgresqlDatabase: airflow
  postgresqlUsername: airflow
  postgresqlPassword: changeme_dbpassword


redis:
  enabled: true
  image:
    tag: "7-alpine"

dags:
  gitSync:
    enabled: true
    repos: |
      https://github.com/jrafaelpena/puj-mlops_-group3.git
    branch: main
    rev: HEAD
    depth: 1
    subPath: proyectos/proyecto-4/apps/airflow/dags

logs:
  persistence:
    enabled: true
    size: 5Gi

webserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - airflow.tudominio.com
    tls:
      - secretName: airflow-tls
        hosts:
          - airflow.tudominio.com

rbac:
  create: true

serviceAccount:
  create: true
  name: airflow-sa

workers:
  podAnnotations: {}
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

scheduler:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

web:
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 600m
      memory: 1Gi