environment:
  executor: KubernetesExecutor

images:
  airflow:
    repository: jrpenagu/airflow-ml
    tag: "1.0"
    pullPolicy: IfNotPresent

airflow:
  config:
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
    AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: s3://airflow-logs
    AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: minio_conn

  connections:
    - id: postgres_default
      type: postgres
      host: postgres
      login: airflow
      password: airflow
      port: 5432
      schema: airflow
    - id: minio_conn
      type: s3
      host: minio
      login: minio
      password: miniopass
      port: 9000
      extra: '{"endpoint_url":"http://minio:9000","region_name":"us-east-1"}'

dags:
  gitSync:
    enabled: true
    repo: https://github.com/jrafaelpena/puj-mlops_-group3.git
    branch: main
    rev: HEAD
    depth: 1
    subPath: proyectos/proyecto-4/apps

postgresql:
  enabled: false
redis:
  enabled: false

externalDatabase:
  host: postgres
  port: 5432
  user: airflow
  password: airflow
  database: airflow
  type: postgres

dags:
  enabled: true
  existingClaim: airflow-dags-pvc
logs:
  enabled: true
  existingClaim: airflow-logs-pvc

service:
  type: ClusterIP