apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-diabetes
  namespace: project-3-mlops
  labels:
    app: locust-diabetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-diabetes
  template:
    metadata:
      labels:
        app: locust-diabetes
    spec:
      containers:
        - name: locust-diabetes
          image: jrpenagu/locust-diabetes:latest
          ports:
            - containerPort: 8089
          env:
            - name: API_URL
              value: http://inference-api:8989
          command: ["locust", "-f", "locustfile.py", "--host", "$(API_URL)"]
---
apiVersion: v1
kind: Service
metadata:
  name: locust-diabetes
  namespace: project-3-mlops
spec:
  type: NodePort
  selector:
    app: locust-diabetes
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30989
