FROM python:3.10.16-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

WORKDIR /app

COPY pyproject.toml .
COPY uv.lock .
COPY .python-version .

ENV UV_LINK_MODE=copy

RUN uv sync --frozen

CMD ["/app/.venv/bin/python", "-m", "mlflow", "server", \
     "--backend-store-uri", "mysql+pymysql://mlflow_user:mlflow@mysql:3306/mlflow_db", \
     "--default-artifact-root", "s3://mlflows3/artifacts", \
     "--host", "0.0.0.0", \
     "--serve-artifacts"]