apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: project-4
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: jrpenagu/streamlit-house-prices:1.0
          ports:
            - containerPort: 8501
          command: ["uv", "run", "streamlit", "run", "streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]
          env:
            - name: API_URL
              value: http://inference-api:8989
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: project-4
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30899