apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-diabetes
  namespace: project-3-mlops
  labels:
    app: streamlit-diabetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-diabetes
  template:
    metadata:
      labels:
        app: streamlit-diabetes
    spec:
      containers:
        - name: streamlit-diabetes
          image: jrpenagu/streamlit-diabetes:latest
          ports:
            - containerPort: 8501
          command: ["uv", "run", "streamlit", "run", "streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]
          env:
            - name: API_URL
              value: http://inference-api:8989
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-diabetes
  namespace: project-3-mlops
spec:
  type: NodePort
  selector:
    app: streamlit-diabetes
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30899