services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi

    ports:
      - "8989:8989"
    
    volumes:
      - './artifacts:/app/artifacts'
  
    command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8989", "--reload"]

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter

    ports:
      - "8888:8888"

    volumes:
      - './artifacts:/work/artifacts'