name: CI for Taller Inference API

on:
  push:
    paths:
      - '4/taller-ci-cd/api-inferencia/**'
      - '4/taller-ci-cd/params.yaml'
  workflow_dispatch:  # Permite la activación manual

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: jrpenagu/fast-api-iris

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.2

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: '4/taller-ci-cd/api-inferencia/app/.python-version'

      - name: Install dependencies
        run: |
          cd 4/taller-ci-cd/api-inferencia/app
          uv sync --frozen

      - name: Train the model
        run: |
          cd 4/taller-ci-cd/api-inferencia/app
          uv run train_model.py
      
      - name: Upload trained model as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: 4/taller-ci-cd/api-inferencia/app/model.pkl

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push with cache
        uses: docker/build-push-action@v6
        with:
          context: 4/taller-ci-cd/api-inferencia
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update manifest with new image tag
        run: |
          sed -i "s|image: .*|image: $IMAGE_NAME:${{ steps.vars.outputs.sha_short }}|" 4/taller-ci-cd/manifests/api.yaml

      - name: Commit updated manifest
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add 4/taller-ci-cd/manifests/api.yaml
          git commit -m "Update image tag to $IMAGE_NAME:${{ steps.vars.outputs.sha_short }}"
          git push